name: trabalho_faculdade
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  mask_text_input_formatter: ^2.5.0
  intl: any
  fl_chart: ^0.63.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  flutter_secure_storage: ^9.0.0
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/